language: python
python:
  - "3.9"
dist: bionic
services:
  - postgresql
  - elasticsearch
env:
  - DEBUG=False ALLOWED_HOSTS=localhost PGS_LIVE_SITE='True' PGS_CURATION_SITE='False'
    DATABASE_NAME=travis_ci_test DATABASE_USER=postgres DATABASE_PASSWORD=password DATABASE_HOST=localhost DATABASE_PORT=5432 DATABASE_PORT_LOCAL=5432
    DATABASE_NAME_2=travis_ci_test_2 DATABASE_USER_2=postgres DATABASE_PASSWORD_2=password DATABASE_HOST_2=localhost DATABASE_PORT_2=5432
    REST_URL_ROOT=http://127.0.0.1/rest/ ELASTICSEARCH_URL_ROOT=http://localhost:9200 SECRET_KEY=1234
before_install:
  - curl https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.15.0-amd64.deb -o elasticsearch.deb
  - sudo dpkg -i --force-confnew elasticsearch.deb
  - sudo chown -R elasticsearch:elasticsearch /etc/default/elasticsearch
  - sudo service elasticsearch start
install:
  - pip install -r requirements.txt
  - pip install requests
  - pip install pandas xlrd openpyxl numpy
before_script:
  - sleep 10
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql -c 'create database travis_ci_test_2;' -U postgres
script:
  - python manage.py test catalog/tests curation/tests rest_api/tests benchmark/tests
